name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
    - main
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npm run lint
        npm run ng -- deploy --base-href=/velopitt/ --name="velopitt automation" --email=${{ secrets.WORKSPACE_EMAIL }}
