name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
    - main
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 24.x
    - name: Send secrets to Env
      env:
        STRAVA_ID: ${{ secrets.STRAVA_ID }}
        STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}
        STRAVA_TOKEN: ${{ secrets.STRAVA_TOKEN }}
    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npm run build:env
        npm run ng -- deploy --base-href=/velopitt/ --name="velopitt automation" --email=${{ secrets.WORKSPACE_EMAIL }}
